package com.example.cs501hw2_funfacts

import android.graphics.Typeface
import android.os.Bundle
import android.text.SpannableString
import android.text.Spanned
import android.text.style.RelativeSizeSpan
import android.text.style.StyleSpan
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.cs501hw2_funfacts.ui.theme.Cs501hw2_funFactsTheme
import kotlin.random.Random
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Shadow
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp


class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            Cs501hw2_funFactsTheme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    FunFacts(
                        modifier = Modifier.padding(innerPadding)
                    )
                }
            }
        }
    }
}

@Composable
fun FunFacts(modifier: Modifier = Modifier) {
    var index by remember { mutableStateOf(Random.nextInt(from = 0, until = 30)) }
    var funfact by remember { mutableStateOf(funFacts[index]) }
    var style by remember { mutableStateOf(MyFont()) }


    Column (modifier = Modifier.padding(30.dp)) {
        Text(
            text = "Here is Your Fun Fact:"
        )
        Text(
            text = "Quote #$index"
        )
        Text(
            text= funfact,
            fontSize = style.randomFontSize,

            color = style.randomColor,

            fontStyle = style.randomStyle,

            fontWeight = style.randomWeight,

            fontFamily = style.randomFontFamily,

        )

        Button(onClick = {
            index += 1
            funfact = funFacts[index % funFacts.size] // iterate through the funFact list
            Log.d("index", index.toString())
            style = MyFont()
        }){
            Text("Randomize a random fun fact")
        }
    }

}

class MyFont(){
    private val styles = listOf(FontStyle.Normal, FontStyle.Italic)
    private val colors = listOf(Color.Cyan,Color.Red,Color.Black,Color.Blue)


    val randomFontSize: TextUnit = Random.nextInt(20,40).sp
    val randomColor: Color = colors[Random.nextInt(colors.size)]
    var randomStyle = styles[Random.nextInt(styles.size)]
    var randomWeight = FontWeight(Random.nextInt(100, 200))
    var randomFontFamily = FontFamily.SansSerif
}


private val funFacts = listOf( // generated by ChatGpt
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "Octopuses have three hearts, nine brains, and blue blood.",
    "Bananas are berries, but strawberries are not.",
    "Wombat poop is cube-shaped!",
    "A day on Venus is longer than a year on Venus.",
    "Sharks have been around longer than trees.",
    "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in heat.",
    "A group of flamingos is called a 'flamboyance'.",
    "Humans share 60% of their DNA with bananas.",
    "Polar bear skin is black, and their fur is actually transparent.",
    "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    "Cats can’t taste sweetness.",
    "Sloths can hold their breath longer than dolphins can.",
    "Turtles can breathe through their butts.",
    "The unicorn is the national animal of Scotland.",
    "Butterflies taste with their feet.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "There are more trees on Earth than there are stars in the Milky Way galaxy.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "Cows have best friends and get stressed when they are separated.",
    "Koalas sleep up to 22 hours a day.",
    "An eagle’s eyesight is about 8 times stronger than that of humans.",
    "Some penguins propose to their mates with a pebble.",
    "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid of Giza.",
    "A snail can sleep for three years at a time.",
    "The first computer virus was created in 1986.",
    "Sea otters hold hands when they sleep to keep from drifting apart.",
    "Kangaroos can’t walk backward.",
    "The heart of a shrimp is located in its head.",
    "The word “nerd” was first coined by Dr. Seuss in his book *If I Ran the Zoo*."
)




@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    Cs501hw2_funFactsTheme {
        FunFacts()
    }
}